dependencies:
  - name: drupal-fpm
    version: 0.1.0
    repository: https://supernami.github.io/helm-charts/
  - name: mariadb
    version: 0.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
