apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: nginx-http
    protocol: TCP
    port: {{ default 80 .Values.service.httpexternalPort }}
    targetPort: {{ default 80 .Values.service.httpinternalPort }}
  - name: nginx-https
    protocol: TCP
    port: {{ default 443 .Values.service.httpsexternalPort }}
    targetPort: {{ default 443 .Values.service.httpsinternalPort }}
  selector:
    app: "{{ template "fullname" . }}"
